In [54]:
import numpy as np



a = np.random.randint ((6, 7), 10)
print(a)


[7 9]


In [55]:
b = np.array([[5,6,3], [2,5,1], [4,4,4]])
print(b)

[[5 6 3]
 [2 5 1]
 [4 4 4]]


In [56]:
np.diag(b)

array([5, 5, 4])

In [57]:
np.diag(np.fliplr(b))

array([3, 5, 4])

In [60]:
arr = np.array([0, 2, 4, 5, 3, 7, 8, 9, 5, 1])


for x in arr:
    if arr[x] % 2 == 1:
        arr[x] *= -1
    else:
        continue

print(arr)


[ 0  2  4 -5 -3  7  8 -9 -5  1]


In [59]:
arr0 = np.array([0,2,4,5,3,7,8,9,5,1])
odd = np.where(arr % 2 == 1)
arr[odd] *= -1

print(arr)

[ 0  2  4  5  3 -7  8  9  5 -1]


In [4]:
##triangle task

A = np.array([0, 0])
B = np.array([0, 3])
C = np.array([1.5, 0])

from numpy import linalg as la
AB = la.norm(A-B)


number = np.array([[1.99, 2.23, 3.35], [5.30, 7.75, 5.65], [1.89, 3.01, 4.56]])
# round off to 1 decimal place

number = np.around(number, decimals = 1)

##add column header
column_header = []

NameError: name 'np' is not defined